export enum PokemonTypes {
    Steel = 'Aço',
    Water = 'Água',
    Dragon = 'Dragão',
    Eletric = 'Elétrico',
    Fairy= 'Fada',
    Ghost = 'Fantasma',
    Fire = 'Fogo',
    Ice = 'Gelo',
    Bug = 'Inseto',
    Fighting = 'Luta',
    Normal = 'Normal',
    Grass = 'Planta',
    Psychic = 'Psíquico',
    Rock = 'Rocha',
    Dark= 'Sombrio',
    Ground = 'Terra',
    Poison = 'Veneno',
    Flying = 'Voador',
  }